CREATE FUNCTION updateBestBid() 
RETURNS TRIGGER
LANGUAGE PLPGSQL AS $$
BEGIN
	UPDATE Auction A
	SET bestBidId = NEW.id
	WHERE A.id = NEW.auctionId;
	RETURN NEW;
END;$$

CREATE TRIGGER updateBestBidTrigger
AFTER INSERT ON Bid
FOR EACH ROW
EXECUTE PROCEDURE updateBestBid();
